name: pytorch-img2img
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.11
  - pytorch=2.4.0
  - torchvision=0.19.0
  - pytorch-cuda=12.1
  - numpy=2.2.6  #numpy=1.24.3
  - scikit-image
  - pip
  - pip:
      - dominate>=2.8.0
      - Pillow>=10.0.0
      - wandb>=0.16.0
      - albumentations>=1.3.0
      - tqdm>=4.67.1
      - ultralytics
